feat: footer 템플릿 추가
bear-bear-bear/vanilla-instagram pull request #23
Opened 2021-08-08 09:36 UTC by pandora2948

2021-08-08 14:01 UTC, galaxy4276 requested changes

2021-08-08 14:01 UTC, galaxy4276 commented on client/app/common/styles/defaults/__variables__.scss
> +$footer-para-color: #a5a5a5;
para 무슨 의미인가요 parameter?

2021-08-08 14:01 UTC, galaxy4276 commented on client/app/templates/legal-policy/legal-policy.pug
> +        |위치
```suggestion
      a(href ="#").footer--navigator-contents.footer--navigator-contents
        |소개
    p
      a(href ="#").footer--navigator-contents.footer--navigator-contents
        |블로그
    p
      a(href ="#").footer--navigator-contents.footer--navigator-contents
        |채용 정보
    p
      a(href ="#").footer--navigator-contents.footer--navigator-contents
        |도움말
    p
      a(href ="#").footer--navigator-contents.footer--navigator-contents
        |API
    p
      a(href ="#").footer--navigator-contents.footer--navigator-contents
        |개인정보처리방침
    p
      a(href ="#").footer--navigator-contents.footer--navigator-contents
        |약관
    p
      a(href ="#").footer--navigator-contents.footer--navigator-contents
        |인기 계정
    p
      a(href ="#").footer--navigator-contents.footer--navigator-contents
        |해시태그
    p
      a(href ="#").footer--navigator-contents.footer--navigator-contents
        |위치
```

재사용 규칙에 어긋나는 거 같아요.
차라리 이렇게 쓰는게 더 편할 듯 한데 어떻게 생각하시나요?

2021-08-08 14:03 UTC, pandora2948 commented on client/app/common/styles/defaults/__variables__.scss
> +$footer-para-color: #a5a5a5;
paragraph 입니다

2021-08-08 14:04 UTC, galaxy4276 commented on client/app/common/styles/defaults/__variables__.scss
> +$footer-para-color: #a5a5a5;
paragraph 는 대게 약어를 사용하지 않습니다.
footer-text-color, footer-font-color 등 다른 이름 고민해보는 것도 좋을 것 같습니다.

2021-08-08 14:05 UTC, galaxy4276 commented on client/app/templates/legal-policy/legal-policy.pug
> +        |위치
클래스 이름이 중복되고 있는 것 같아요.

2021-08-08 14:06 UTC, pandora2948 commented on client/app/templates/legal-policy/legal-policy.pug
> +        |위치
```suggestion
      a(href ="#").footer--navigator-contents--about
        |소개
    p
      a(href ="#").footer--navigator-contents--blog
        |블로그
    p
      a(href ="#").footer--navigator-contents--careers
        |채용 정보
    p
      a(href ="#").footer--navigator-contents--help
        |도움말
    p
      a(href ="#").footer--navigator-contents--api
        |API
    p
      a(href ="#").footer--navigator-contents--privacy
        |개인정보처리방침
    p
      a(href ="#").footer--navigator-contents--terms
        |약관
    p
      a(href ="#").footer--navigator-contents--profiles
        |인기 계정
    p
      a(href ="#").footer--navigator-contentshash-tag
        |해시태그
    p
      a(href ="#").footer--navigator-contents--location
        |위치
```
중복되는 부분 수정해보았습니다

2021-08-08 14:08 UTC, galaxy4276 commented on client/app/templates/legal-policy/legal-policy.pug
> +        |위치
p 와 a 로 구성된 태그 구성에서 전체적으로 동일한 스타일을 변하지 않고 유지하게 될거라고 생각하는데 어떻게 생각하시나요?
현재 모든 클래스는 재사용이 불가능해보입니다.

2021-08-08 14:10 UTC, galaxy4276 commented on client/app/templates/legal-policy/legal-policy.pug
> +        |위치
`
 .footer--navigator-contents {
     // style definition
 }
`
예를 들어, 이렇게 일관성있는 스타일을 유지하게 끔 해줍니다.
다른 의도가 있다면 현재 Request Change 는 Resolve conversation 을 눌러 닫기해주시고 승인 요청해주세요.

2021-08-08 14:13 UTC, bear-bear-bear requested changes
코멘트 부분 전부 수정 바래요.
반응형 동작 여부는 코멘트가 전부 resolve 되면 그 때 확인하겠습니다.
지금은 단순히 코드만 보고 리뷰한 것

고생하셨습니다

2021-08-08 14:13 UTC, bear-bear-bear commented on client/app/common/styles/defaults/__variables__.scss
> +$footer-para-color: #a5a5a5;
paragraph 아닐까요 html `<p>` 약자

2021-08-08 14:13 UTC, bear-bear-bear commented on client/app/common/styles/defaults/__mixins__.scss
> +}
무슨 wrap의 width 인가요? 공용 mixin 파일에서 이렇게 어디에 쓰일지 모르는 의미불명 네임은 지양해주세요

2021-08-08 14:13 UTC, bear-bear-bear commented on client/app/common/styles/defaults/__mixins__.scss
> +}
모든 mixin을 한 곳에 모으기 불편하다면, 여러 mixin 파일을 한개의 scss에서 import 하여 모으는 구조로 변경해도 됩니다

2021-08-08 14:13 UTC, bear-bear-bear commented on client/app/common/styles/defaults/__variables__.scss
> +$footer-para-color: #a5a5a5;
color 변수는 '어느곳에 쓰이는 컬러' 가 아니라, 
![image](https://user-images.githubusercontent.com/57123802/128634755-288d219a-87ae-4ef2-882d-5ea53b52f40b.png)
위와 같이 '어떤 색깔' 인지만 표기해주셔야 재사용성이 높아집니다.

2021-08-08 14:13 UTC, bear-bear-bear commented on client/app/templates/legal-policy/legal-policy.pug
> +  nav.footer--navigator
BEM의 잘못된 사용

2021-08-08 14:13 UTC, bear-bear-bear commented on client/app/templates/legal-policy/legal-policy.pug
> +      a(href ="#").footer--navigator-contents.footer--navigator-contents--locations
* BEM의 잘못된 사용
* href 와 = 사이의 불필요한 띄어쓰기
* 각각의 링크에 각각 다른 클래스명을 줄 필요가 있었나요? grid를 사용하시나.. 굳이 grid-area로 배치할 정도의 구성은 아니던데요

2021-08-08 14:13 UTC, bear-bear-bear commented on client/app/templates/legal-policy/legal-policy.scss
> +  a {
mixin 구조가 어떻게 되어있는지는 모르나, p 안에 a가 들어있는 상황에 두 개 엘리먼트에 동일한 스타일을 부여할 필요가 있나요?

2021-08-08 14:14 UTC, bear-bear-bear commented on client/app/common/styles/defaults/__variables__.scss
> +$footer-para-color: #a5a5a5;
변수만 보고도 이게 어떤색인지 한 눈에 알 수도 있게되구요.

2021-08-08 14:16 UTC, galaxy4276 commented on client/app/common/styles/defaults/__variables__.scss
> +$footer-para-color: #a5a5a5;
선언을 고치기보단 삭제 후 --color-scale-gray 같은 값이 기존에 존재한다면 그 값을 활용하는 것을 권장드립니다.

2021-08-08 14:17 UTC, galaxy4276 commented on client/app/templates/legal-policy/legal-policy.pug
> +  nav.footer--navigator
BEM! 💥💥💥💥

2021-08-08 14:21 UTC, bear-bear-bear commented on client/app/common/styles/defaults/__variables__.scss
> +$footer-para-color: #a5a5a5;
@galaxy4276 아 저건 깃허브 f12열면 보이는 컬러변수입니다

2021-08-08 15:37 UTC, bear-bear-bear requested changes

2021-08-08 15:37 UTC, bear-bear-bear commented on client/app/common/styles/defaults/__mixins__.scss
>  }
@mixin은 '재사용'을 위한겁니다. 적어주신 footer-text-design 이 어디에 재사용될지 모르겠습니다. mixin으로 따로 빼야할 정도로 재사용성이 큰가요?

2021-08-08 15:37 UTC, bear-bear-bear commented on client/app/common/styles/defaults/__variables__.scss
> +$footer-text-color--gray: #a5a5a5;
직전 코멘트를 잘못 이해하신 듯 합니다.

위 변수를 컬러변수의 올바른 예시로 고친다면 다음과 같습니다.
``` scss
$--color-gray: #a5a5a5;
```

이후 다른 종류의 gray가 추가되어 gray의 종류가 많아지면,
명도나 채도에 따라 넘버링하여 구분합니다.

``` scss
$--color-gray-0: #f0f6fc;
$--color-gray-1: #b1bac4;
$--color-gray-2: #a5a5a5;
```

근데 컬러변수는 팀원간 상의 하에 추가하시는 것이 좋습니다.
오늘 회의에서 컬러 상의하여 정하라고 얘기했는데, 저 gray는 팀원간 상의 하에 결정된 컬러인가요?

2021-08-08 15:37 UTC, bear-bear-bear commented on client/app/templates/legal-policy/legal-policy.pug
> +        |소개
nav에 있는 Anchor 들을 semantic하게 나열하려면, 보통
``` pug
nav
  ul
    li
      a
    li
      a
    li
      a
```
형식을 많이 띕니다.

2021-08-08 15:37 UTC, bear-bear-bear commented on client/app/templates/legal-policy/legal-policy.pug
> +        |위치
* 위의 `p` 태그에는 SCSS에서 모두 같은 스타일이 부여되어 있지만, 서로 다른 클래스를 가지고 있고 해당 클래스들은 전혀 사용되지 않고 있습니다. 추후 사용하려고 만들어둔게 아니라면 삭제 바랍니다.
* 반복되는 코드들이 보이시나요? pug에선 이런 단순 반복 코드에 '반복문'을 사용할 수 있습니다. 아래 처럼요.
``` pug
nav
  ul
    -
      const links = [
        { desc: '소개', href: '#' },
        { desc: '블로그', href: '#' },
        { desc: '채용 정보', href: '#' },
        // ...
      ];

    each link in links
      li
        a(href= link.href)= link.desc
```

-- [pug 에서 반복문, js코드 사용하기](https://pugjs.org/language/code.html)
-- [pug 에서 js 코드 사용시 multiline](https://github.com/pugjs/pug/issues/502#issuecomment-147733629)

2021-08-08 15:37 UTC, bear-bear-bear commented on client/app/templates/legal-policy/legal-policy.pug
> +  p.legal-policy--copyright
잘못된 BEM

2021-08-08 16:12 UTC, galaxy4276 reviewed
진행하시면서 조금이라도 막힌다 싶으신거 있으시면 질문주세요.

2021-08-09 02:32 UTC, bear-bear-bear commented on client/app/templates/legal-policy/legal-policy.pug
> +        |위치
반복문 사용은 필수가 아닙니다 애초에 저희 계획이 pug를 딥하게 쓰는게 아니였으니까요. 이런 선택지도 있다. 정도로 이해하시면 될 것 같습니다

2021-08-09 18:04 UTC, bear-bear-bear commented on client/app/templates/legal-policy/legal-policy.pug
> +          |위치
href ="#"
띄어쓰기 왜 하는거에요??

2021-08-09 18:04 UTC, bear-bear-bear commented on client/app/templates/legal-policy/legal-policy.pug
> +          |위치
일단 시멘틱 변경 감사합니다

2021-08-10 04:56 UTC, pandora2948 commented on client/app/templates/legal-policy/legal-policy.pug
> +          |위치
별다른 뜻 없습니다 가독성 향상을 위해 수정하였습니다.

2021-08-10 05:39 UTC, galaxy4276 commented
__variables__.scss 와 충돌이 발생합니다. 해결해주세요.
** Guide **
* fork 에서 footer-template 와 master 머지 후 발생하는 컨플릭트 해결해주세요.
* __variables__.scss 에서 빈 줄에 대한 충돌일 확률이 높습니다.

2021-08-10 05:41 UTC, galaxy4276 commented
해결해드렸습니다. 기존 작업하시는 브랜치 Pull 받고 작업해주세요.

2021-08-10 06:02 UTC, galaxy4276 approved these changes, later dismissed

2021-08-10 06:08 UTC, galaxy4276 approved these changes

2021-08-10 06:14 UTC, bear-bear-bear approved these changes

2021-08-10 06:14 UTC, merged