feat: 서버 실행 테스트 작성
bear-bear-bear/vanilla-instagram pull request #31
Opened 2021-08-10 05:22 UTC by galaxy4276

## Summary
* 테스트 라이브러리 @types 를 설치하였습니다.
* 서버 실행 테스트를 작성하였습니다.

2021-08-10 05:45 UTC, galaxy4276 commented
CI 에서 발생하는 오류로 잠시 보류

2021-08-14 04:46 UTC, An-jihyun submitted a review, later dismissed

2021-08-14 04:53 UTC, pandora2948 approved these changes, later dismissed
고생하셨습니다

2021-08-14 04:54 UTC, bear-bear-bear requested changes
잠시만요

2021-08-14 05:05 UTC, bear-bear-bear commented on server/test/e2e/server.test.ts
> +import runningStatusApp from '../../src';
path alias 적용되어 있습니다. 변경하여 반영하겠습니다

2021-08-14 05:07 UTC, bear-bear-bear submitted a review, later dismissed
고생하셨어용
테스트도 ts로 하는걸 권장하시나요??

2021-08-14 05:07 UTC, An-jihyun submitted a review, later dismissed

2021-08-14 05:11 UTC, galaxy4276 commented
복잡한 테스트를 작성할 때, 타입으로 얻는 이점이 있습니다.
CI 오류 수정해주세요.
jest.config 에서 Path alias 를 수정했으면 tsconfig 에서도 수정해줘야 하는 것 같습니다.

2021-08-14 05:40 UTC, bear-bear-bear requested changes

2021-08-14 05:40 UTC, bear-bear-bear commented on server/tsconfig.json
> +      "@root/*": ["./src/*"]
에? 여기 alias를 변경하셨네요?

2021-08-14 05:43 UTC, bear-bear-bear commented on server/tsconfig.json
> +      "@root/*": ["./src/*"]
프런트측 webpack alias와도 통일시킨거라 곤란스한데

2021-08-14 06:25 UTC, galaxy4276 commented on server/tsconfig.json
> +      "@root/*": ["./src/*"]
기존 '@/' 명령어는 잘 먹히던가요?

2021-08-14 06:31 UTC, bear-bear-bear commented on server/tsconfig.json
> +      "@root/*": ["./src/*"]
확인 안해봤지만 아마 같은 에러 날거라 예상합니다

2021-08-14 06:31 UTC, bear-bear-bear commented on server/tsconfig.json
> +      "@root/*": ["./src/*"]
![image](https://user-images.githubusercontent.com/57123802/129437471-97b147a0-e2d4-4057-8002-518ad934a81c.png)

변경 시도 중

2021-08-14 15:00 UTC, bear-bear-bear submitted a review, later dismissed

2021-08-14 15:05 UTC, pandora2948 approved these changes, later dismissed

2021-08-14 15:27 UTC, bear-bear-bear approved these changes
fuc

2021-08-14 15:59 UTC, pandora2948 approved these changes

2021-08-14 15:59 UTC, merged