feat: 로그인페이지 responsive web 구현 - 백동재
bear-bear-bear/vanilla-instagram pull request #35
Opened 2021-08-10 22:03 UTC by galaxy4276

2021-08-10 22:13 UTC, bear-bear-bear requested changes
#32 확인 안하셨나요?

2021-08-10 22:14 UTC, galaxy4276 commented
> #32 확인 안하셨나요?

죄송합니다..크흑헉 ㅠㅠㅠㅠㅠ 😫😫😫😫😫😫😫😫😫😫😫

2021-08-10 22:18 UTC, bear-bear-bear commented
팀장님 말고 ㅋㅋㅌㅋ @pandora2948

2021-08-11 07:29 UTC, galaxy4276 reviewed
검사 완료

2021-08-11 07:30 UTC, pandora2948 approved these changes, later dismissed

2021-08-11 14:03 UTC, bear-bear-bear requested changes

2021-08-11 14:03 UTC, will-kim-querypie commented on client/app/common/styles/defaults/__mixins__.scss
> +}
사용법이 아주 많이 틀리셨어요.
제가 올려드린 예제대로 안한다고 해도 잘못된 방법이고,
올려드린 예제대로 한거라고 하면
``` SCSS
@content
```
를 잘못 이해하신 것 같아요 아마

2021-08-11 14:03 UTC, bear-bear-bear commented on client/app/common/styles/defaults/__mixins__.scss
> +}
#33 내용 다시 이해해주세요

2021-08-11 14:03 UTC, will-kim-querypie commented on client/app/templates/auth-form/auth-form.scss
> +  overflow: hidden;
히든을 써야할 이유가 있었나요? (질문)

2021-08-11 14:05 UTC, bear-bear-bear commented on client/app/common/styles/defaults/__mixins__.scss
> +}
미안합니다 33이 아니라 32 #32

2021-08-11 14:08 UTC, pandora2948 commented on client/app/templates/auth-form/auth-form.scss
> +  overflow: hidden;
스크롤 생성을 통제하기 위해서 작성하였습니다.

2021-08-11 14:11 UTC, bear-bear-bear commented on client/app/templates/auth-form/auth-form.scss
> +  overflow: hidden;
인스타그램 스타일 구조상 overflow가 발생하지 않게 설계되는게 맞는 것 같은데, overflow가 발생되고 scroll이 생겼다면 뭔가 근본적인 문제가 있는 것 같네요

2021-08-11 14:11 UTC, bear-bear-bear commented on client/app/templates/auth-form/auth-form.scss
> +  overflow: hidden;
SCSS를 한 줄 한 줄 확인해본건 아니라 추측입니다

2021-08-11 14:12 UTC, bear-bear-bear commented on client/app/templates/auth-form/auth-form.scss
> +  overflow: hidden;
form에 고정 height을 줬다든가?

2021-08-11 14:13 UTC, pandora2948 commented on client/app/templates/auth-form/auth-form.scss
> +  overflow: hidden;
nothing problum i guess

2021-08-11 14:17 UTC, bear-bear-bear commented on client/app/templates/auth-form/auth-form.scss
> +  overflow: hidden;
is problem

2021-08-12 04:26 UTC, pandora2948 approved these changes

2021-08-12 07:44 UTC, will-kim-querypie approved these changes
고생띠

2021-08-12 08:21 UTC, merged