feat: 회원가입 페이지 생성
bear-bear-bear/vanilla-instagram pull request #36
Opened 2021-08-11 14:22 UTC by pandora2948

Closes #37

2021-08-12 15:01 UTC, bear-bear-bear commented
#37 이에요! @galaxy4276

2021-08-12 17:02 UTC, galaxy4276 submitted a review, later dismissed

2021-08-13 07:37 UTC, bear-bear-bear requested changes

2021-08-13 07:37 UTC, bear-bear-bear commented on client/app/templates/auth-form/auth-form.scss
> +  }
footer를 여기서 조작하나요?

2021-08-13 07:55 UTC, pandora2948 commented on client/app/templates/auth-form/auth-form.scss
> +  }
deleted malfunction code

2021-08-13 09:14 UTC, bear-bear-bear commented
동작 안하는 코드 였나ㅓ요??

2021-08-13 09:14 UTC, bear-bear-bear approved these changes
고생띠

2021-08-13 11:33 UTC, galaxy4276 approved these changes

2021-08-13 11:33 UTC, merged