docs: 추천피드, 컨테이너 생성을 위한 작업 추가
bear-bear-bear/vanilla-instagram pull request #43
Opened 2021-08-12 17:02 UTC by An-jihyun

▪container-ui 템플릿 생성을 위한 폴더를 생성했습니다.
-컨테이너ui: templates/container-ui

▪suggested-feed page 생성을 위한 폴더를 생성했습니다.
-추천피드: pages/suggested-feed page

▪인스타 로고 svg 파일을 추가했습니다.
-insta-logo-text.svg

▪home페이지의 페이지 링크명 수정 및 추천 피드 페이지 링크를 추가했습니다.

2021-08-14 04:27 UTC, galaxy4276 approved these changes, later dismissed

2021-08-14 04:30 UTC, galaxy4276 approved these changes, later dismissed
고생하셨습니다. 👍👍👍

2021-08-14 04:48 UTC, bear-bear-bear commented
@galaxy4276  아직 draft입니다

2021-08-14 04:49 UTC, galaxy4276 commented
> @galaxy4276 아직 draft입니다

[Draft](https://www.youtube.com/watch?v=5tHofUXNibc)

2021-08-14 14:59 UTC, pandora2948 commented
> > @galaxy4276 아직 draft입니다
> 
> [Draft](https://www.youtube.com/watch?v=5tHofUXNibc)

죄송한데 그건 drift 같습니다.

2021-08-15 16:02 UTC, pandora2948 commented on client/app/common/styles/defaults/__mixins__.scss
> +
변수 선언을 mixins에 하신 이유가 있을까요?

2021-08-15 16:09 UTC, pandora2948 commented on client/app/templates/container-ui/container-ui.scss
> +    // outline: 0;
주석이 존재합니다!

2021-08-15 16:11 UTC, pandora2948 commented on client/app/templates/container-ui/container-ui.scss
> +  height: 1000vh;
이 부분은 일단 무한 스크롤을 구현하기 위해 작성된건가요?

2021-08-15 16:16 UTC, An-jihyun commented on client/app/common/styles/defaults/__mixins__.scss
> +
해당사항에 대한 설명을 추가했습니다. 확인부탁드립니다.

2021-08-15 16:28 UTC, pandora2948 requested changes

2021-08-15 16:28 UTC, pandora2948 commented on client/app/templates/container-ui/container-ui.scss
> +  border-bottom: 1px solid #dbdbdb;
무채색은 variables에 채도 별로 선언해두었습니다.
혹시 이외의 색을 사용 하시는 거 라면 variables에 선언 부탁 드립니다.

2021-08-15 16:35 UTC, An-jihyun commented on client/app/templates/container-ui/container-ui.scss
> +    // outline: 0;
해결 완료

2021-08-15 16:35 UTC, An-jihyun commented on client/app/templates/container-ui/container-ui.scss
> +  height: 1000vh;
임시 test code로 test page로 이동했습니다. 해결 완료

2021-08-15 16:36 UTC, An-jihyun commented on client/app/templates/container-ui/container-ui.scss
> +  border-bottom: 1px solid #dbdbdb;
해결하러 가겠스비낟

2021-08-15 16:44 UTC, bear-bear-bear commented on client/app/templates/container-ui/container-ui.scss
> +  border-bottom: 1px solid #dbdbdb;
지현이 해결 안하고 김치전 먹고 있습니다.

2021-08-15 16:46 UTC, galaxy4276 commented on client/app/templates/container-ui/container-ui.scss
> +  border-bottom: 1px solid #dbdbdb;
![image](https://user-images.githubusercontent.com/50310464/129485923-88da61fe-ca84-4e73-8e49-ea8b01e10098.png)
찹쌀 배추전은 고려해보지 않으셨나요?

2021-08-15 16:48 UTC, bear-bear-bear commented on client/app/templates/container-ui/container-ui.scss
> +  border-bottom: 1px solid #dbdbdb;
와 마렵네

2021-08-15 16:48 UTC, bear-bear-bear commented on client/app/templates/container-ui/container-ui.scss
> +  border-bottom: 1px solid #dbdbdb;
먹을거 가져온다

2021-08-15 16:48 UTC, pandora2948 commented on client/app/templates/container-ui/container-ui.scss
> +  border-bottom: 1px solid #dbdbdb;
햇반 가져와

2021-08-15 16:49 UTC, An-jihyun commented on client/app/templates/container-ui/container-ui.scss
> +  border-bottom: 1px solid #dbdbdb;
전은 킹정이죠 ㅠ

2021-08-15 17:33 UTC, An-jihyun commented on client/app/templates/container-ui/container-ui.scss
> +  border-bottom: 1px solid #dbdbdb;
해결 완료

2021-08-15 17:40 UTC, galaxy4276 approved these changes

2021-08-15 17:40 UTC, bear-bear-bear approved these changes
pug BEM와 scss가 명품이네요

2021-08-15 17:52 UTC, pandora2948 commented on client/app/common/styles/defaults/__variables__.scss
> +$color--gray-2: #8e8e8e;
음 컬러값 변경을 진행한 이유를 알수있을까요?

2021-08-15 18:01 UTC, pandora2948 commented on client/app/templates/container/container.scss
> +}
scss 깔끔하네요 굉장해 엄청나!
![image](https://user-images.githubusercontent.com/80594323/129487941-89093271-52e9-4d91-b715-f9c1d9bc6a9b.png)

2021-08-15 18:02 UTC, galaxy4276 commented on client/app/templates/container/container.scss
> +}
![image](https://user-images.githubusercontent.com/50310464/129487955-8b49c3d1-aa90-4bc9-820d-7c5cbfff41a9.png)

2021-08-16 04:41 UTC, An-jihyun commented on client/app/common/styles/defaults/__variables__.scss
> +$color--gray-2: #8e8e8e;
임의로 인스타에서 쓰이는 색과 비슷한 색상을 뽑아뒀던 것에서 인스타에서 쓰이는 원본 색으로 몇몇 색상을 수정하였습니다.

2021-08-16 04:41 UTC, An-jihyun commented on client/app/templates/container/container.scss
> +}
![image](https://user-images.githubusercontent.com/76841930/129512223-e9959316-c40d-48a9-8707-a72729ddea9e.png)

압도적 감사

2021-08-16 05:00 UTC, pandora2948 approved these changes
고생하셨습니다!

2021-08-16 06:08 UTC, merged