feat: 인풋의 라벨을 입력에 따라 이동하는 기능 구현
bear-bear-bear/vanilla-instagram pull request #61
Opened 2021-08-25 15:10 UTC by pandora2948

2021-09-09 17:52 UTC, bear-bear-bear requested changes
DynamicInput.js 파일에 대해 약간의 리팩터링을 하여 푸시했습니다.

1. 코드간 개행문자로 가독성 향상
2. 공통 클래스네임을 객체 프로퍼티로 분리
3. 각 메서드에 JSDoc 설명 추가 (@desc)
4. Dynamic… -> dynamic...   파일명 수정

2021-09-09 17:52 UTC, bear-bear-bear commented on client/app/pages/sign-up/sign-up.js
> +  pattern: '^([가-힣]{2,20}|[a-zA-Z]+[a-zA-Zs]{2,20})$',
1. s 오타지요?
2. [a-zA-Z]+ 는 들어가야 하나요?

2021-09-09 17:52 UTC, bear-bear-bear commented on client/app/pages/verification/verification.js
> +dynamicInput.setDefaultStyle();
1. setDefaultStyle 두번 쓰셨어요
2. inputDetector 안쓴건 의도된 건지요?

2021-09-09 17:52 UTC, bear-bear-bear commented on client/app/pages/verification/verification.pug
>      label +82 10-0000-0000 으로 발송된 보안 코드를 확인해 주세요
라벨도 dynamic 만드신거에서 확인할 수 있는데

```js
const verificationInput = dynamicInput.create('', {
  type: 'text',
  required: 'required',
});
```

저렇게 빈 문자열로 비워놓고 굳이 pug에서 생성한 이유가 있으신가요?

2021-09-09 17:53 UTC, galaxy4276 commented
제가 준재형 시켜서 리팩터링햇습니다.

2021-09-09 18:31 UTC, pandora2948 commented on client/app/pages/verification/verification.js
> +dynamicInput.setDefaultStyle();
1번 해결했고 2번은 의도한거 맞습니다, 애초에 인풋 생성할때 라벨도 빈 문자열로 생성하였습니다.

2021-09-09 18:32 UTC, pandora2948 commented on client/app/pages/verification/verification.pug
>      label +82 10-0000-0000 으로 발송된 보안 코드를 확인해 주세요
해당 문자열은 인풋 내부에 들어가는거보다 인풋 외부에서 보여지는게 더 사용자 입장에서 봤을때 나을거라고 생각해서 그랬습니다

2021-09-09 18:33 UTC, pandora2948 commented on client/app/pages/sign-up/sign-up.js
> +  pattern: '^([가-힣]{2,20}|[a-zA-Z]+[a-zA-Zs]{2,20})$',
수정하였습니다.

2021-09-10 07:07 UTC, bear-bear-bear commented on client/app/pages/verification/verification.pug
>      label +82 10-0000-0000 으로 발송된 보안 코드를 확인해 주세요
회의때 말한 방법 확인할것

2021-09-12 12:06 UTC, bear-bear-bear requested changes

2021-09-12 12:06 UTC, bear-bear-bear commented on .github/workflows/node.js.yml
> +          mysql password: 'sungsimdang'
??

2021-09-12 12:06 UTC, bear-bear-bear commented on client/app/common/entry.js
> +  const source = new EventSource(`http://localhost:8001/sse`);
?????? 이게 왜 동재님 변경사항에 있죠?

2021-09-12 12:07 UTC, pandora2948 commented on client/app/common/entry.js
> +  const source = new EventSource(`http://localhost:8001/sse`);
잘 모르겠습니다 한번 확인해보겠습니다

2021-09-12 12:07 UTC, bear-bear-bear commented
컨플릭트 심각하게 잘못해결하신 듯 한데

2021-09-12 12:43 UTC, bear-bear-bear requested changes

2021-09-12 12:43 UTC, bear-bear-bear commented on client/app/pages/login/login.js
> +const identificationInput = dynamicInput.create('전화번호 혹은 사용자 이름', {
identificationInput  .. 취향이지만, 그냥 idInput이 훨씬 가독성 좋을 것 같네요. 상세한 이름도 좋지만, 범용적인걸로.

2021-09-12 12:43 UTC, bear-bear-bear commented on client/app/pages/login/login.js
> +  pattern: '[\\w.]{6,20}',
요건 무슨 정규식이져????

2021-09-12 12:43 UTC, bear-bear-bear commented on client/app/pages/sign-up/sign-up.js
> +  pattern: '^(?=1)[d]{0,10}$',
1. 국제번호 지원 안한 점
2. 한국번호만 지원할거면 길이는 고정값이지 않나요?
3. (?=1) 얘는 뭐고
4. [d] 얘는 뭔가요
5. 테스트는 하고 올리셨나요?

2021-09-12 12:43 UTC, bear-bear-bear commented on client/app/pages/sign-up/sign-up.js
> +  pattern: '[w.]{6,20}',
테스트 하고 올리셨나요?

2021-09-12 12:43 UTC, bear-bear-bear commented on client/app/pages/verification/verification.js
> +});
인증번호에도 패턴이 들어가면 좋습니다. 숫자 6자리.

2021-09-13 04:47 UTC, bear-bear-bear commented on client/app/pages/verification/verification.js
> +dynamicInput.setDefaultStyle();
[코멘트 확인](https://github.com/bear-bear-bear/vanilla-instagram/pull/61#discussion_r705946116)

2021-09-27 05:26 UTC, pandora2948 commented on client/app/pages/login/login.js
> +const identificationInput = dynamicInput.create('전화번호 혹은 사용자 이름', {
수정하였습니다.
무려 15일 만에!

2021-09-27 05:34 UTC, pandora2948 commented on client/app/pages/login/login.js
> +  pattern: '[\\w.]{6,20}',
한글을 제외한 문자 6자리부터 20자리까지 받아들이는 정규식입니다

2021-09-27 05:57 UTC, bear-bear-bear commented on client/app/pages/login/login.js
> +  pattern: '[\\w.]{6,20}',
제가 왜 이의 제기 했었는지 모르겠네요 미안합니다

2021-09-27 10:54 UTC, pandora2948 commented on client/app/pages/verification/verification.js
> +});
problem solved

2021-09-27 11:33 UTC, pandora2948 commented on client/app/pages/sign-up/sign-up.js
> +  pattern: '^(?=1)[d]{0,10}$',
수정했습니다 확인 부탁드립니다.

2021-09-27 11:46 UTC, pandora2948 commented on client/app/pages/sign-up/sign-up.js
> +  pattern: '[w.]{6,20}',
변경한 식으로 테스트 하였습니다

2021-09-27 12:07 UTC, bear-bear-bear requested changes

2021-09-27 12:07 UTC, bear-bear-bear commented on client/app/lib/regex.js
> +  username: '[\\w]{6,20}',
. 이 안들어갔네요. 노션 정규식 확인

2021-09-28 02:31 UTC, pandora2948 commented on client/app/lib/regex.js
> +  username: '[\\w]{6,20}',
수정하였습니다!

2021-09-29 05:09 UTC, pandora2948 commented on client/app/pages/verification/verification.pug
>      label +82 10-0000-0000 으로 발송된 보안 코드를 확인해 주세요
정적 컨텐츠로 변경 완료하였습니다.
확인 부탁드립니다.

2021-09-29 05:56 UTC, galaxy4276 approved these changes
😁😁

2021-09-29 08:20 UTC, bear-bear-bear approved these changes
고생하셨어용 다음 작업 이미지 슬라이드인가요?

2021-09-29 16:31 UTC, merged

2021-09-29 16:32 UTC, pandora2948 commented
> 고생하셨어용 다음 작업 이미지 슬라이드인가요?

맞습니다